plugins: 
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: ./eslintrc.js
      extensions:
        - .es6
        - .js
        - .jsx
        - .mjs
        - .ts
        - .tsx